# This file is a template, and might need editing before it works on your project.
image: node:10

stages:
  - install
  - test
  - build

cache:
  paths:
    - node_modules/

install:
  stage: install
  script:
    - yarn install
  artifacts:
    paths:
      - node_modules/

testing:
  stage: test
  script: yarn test

build:
  stage: build
  script:
    - yarn predeploy
    - yarn build
  artifacts:
    paths:
      - public
  only:
    - latest
